### ISSUE TITLE
Biolab frisking guard's voice is extremely quiet or silent

### ISSUE THREAD

**Issue by edisleado** [edisleado/Hitman-Bug-Tracker#1]
Can't hear Sapienza Biolab frisking guard telling you that you'll need to be frisked beforehand, nor can anything be heard from him in the process of frisking.

Originally reported by WRP_Beater on Hitmanforum on April 27th, 2016.

According to Hitmanforum user HMBM47:

> I am able to get his voice working by simulating 7.1 sound with Razer Surround.
> But if everything is set to stereo, all you hear is a faint echo or absolutely nothing.
> edit: After alt tabbing out of the game and testing it out again, his voice is silent again. 
> Either way, his voice is still bro-ked.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/18752617/17463185/c186397e-5c8e-11e6-9883-7d3f833e53d2.png)

**Comment by wachsmuth** [comment]
Can't reproduce this bug as of the November patch. It appears to have been fixed.

**Comment by edisleado** [comment]
Hmm, I'm still experiencing this in the latest November patch. I walked up the frisking point with a housekeeper disguise and the frisking guard's voice was still whisper quiet.

**Comment by HMBM47** [comment]
Curious. It's fixed on my end as well. I'm on PC.

**Comment by HMBM47** [comment]
Upon further inspection if you stand close to him the audio is the proper volume, so when you get frisked it's the proper level. BUT if you trigger him to talk a little further away, near the archway it can be muffled.

**Comment by leet-it-b** [comment]
january update
https://hitman.com/news/january-update-release-notes
> Fixed an issue where the dialogue from a guard in the wine cellar could be difficult to hear when standing in a specific place

**Comment by edisleado** [comment]
Seems to be fixed for me as of the January patch. Closing!
