### ISSUE TITLE
Bangkok - 5 instances of Hotel Staff consistently having conversations with themselves in two distinct voices (This seems to happen to most Hotel Staff that have conversations with other Hotel Staff)

### ISSUE THREAD

**Issue by HMBM47** [edisleado/Hitman-Bug-Tracker#64]
![hitman 2016-08-17 17-28-14](https://cloud.githubusercontent.com/assets/20890580/17758148/c52ce21a-64a1-11e6-95fc-36634ea86326.jpg)
![hitman 2016-08-17 17-35-35](https://cloud.githubusercontent.com/assets/20890580/17783376/ad86c118-652c-11e6-82a4-c75537b5d16b.jpg)
video:https://youtu.be/F7TT2f6YuXw

**Comment by HMBM47** [comment]
I found another instance of another Female Hotel Staff Member talking to herself. The first conversation she has is normal, then the next conversation is with herself, and the voices are completely different from the first conversation.
![hitman 2016-08-18 10-03-35](https://cloud.githubusercontent.com/assets/20890580/17783313/588e5a0e-652c-11e6-96ba-9ce085bf1865.jpg)
![hitman 2016-08-18 10-03-52](https://cloud.githubusercontent.com/assets/20890580/17783315/5ad79a28-652c-11e6-8946-407b4c82f77b.jpg)
video:https://youtu.be/iD31E_RE1To

**Comment by HMBM47** [comment]
Found yet another instance of this. This time it's a male Hotel Staff member with a male and female voice. All these conversations are obviously supposed to take place between the other person nearby but for whatever reason the voices and mouth movement come from the one person.
![hitman 2016-08-18 12-28-28](https://cloud.githubusercontent.com/assets/20890580/17787968/4b5307ea-6540-11e6-9d01-570d1d129ddd.jpg)
![hitman 2016-08-18 12-28-44](https://cloud.githubusercontent.com/assets/20890580/17787974/4d48c882-6540-11e6-9c25-cdd006742e88.jpg)
video:https://youtu.be/nlZu9p3tiKU

**Comment by HMBM47** [comment]
One more.
![hitman 2016-08-18 12-39-53](https://cloud.githubusercontent.com/assets/20890580/17788327/fa1e4c84-6541-11e6-894d-4df39270fb03.jpg)
![hitman 2016-08-18 12-40-13](https://cloud.githubusercontent.com/assets/20890580/17788328/fbc1caf2-6541-11e6-9dec-423fdc1359a0.jpg)
video:https://youtu.be/iY3QRCGyPC8

**Comment by HMBM47** [comment]
One more time.
Male Hotel Staff has a normal conversation about falling coconuts. Then his voice changes and he "has a conversation with a woman" all from his own mouth.
![hitman 2016-08-18 13-50-51](https://cloud.githubusercontent.com/assets/20890580/17790501/90dd632c-654b-11e6-9152-dfe15ae7d475.jpg)
![hitman 2016-08-18 13-51-10](https://cloud.githubusercontent.com/assets/20890580/17790502/932e4b5a-654b-11e6-9eec-17b01842c895.jpg)
video:https://youtu.be/5UAh-VN8rR0

**Comment by HMBM47** [comment]
One more time. Normal conversation with guy about falling coconuts. 
Then his voice changes and he "has a conversation with a woman" all from his mouth.

**Comment by leet-it-b** [comment]
Should be fixed now
>Fixed npc's in Bangkok which had voice from other sex.
https://www.reddit.com/r/HiTMAN/comments/5fbr6u/stuff_fixes_not_in_the_patch_notes/

**Comment by HMBM47** [comment]
I didn't see your post. But nope, this still hasn't been fixed. Even after the latest January update this is still an issue.
